### ISSUE TITLE
Doesn't work when using `micromark-extension-gfm-table`

### ISSUE THREAD

**Issue by binyamin** [wataru-chocola/micromark-extension-definition-list#72]
Original issue is over at https://github.com/micromark/micromark-extension-gfm-table/issues/8. Note that it _may_ be an issue on their side.

**Comment by wataru-chocola** [comment]
@binyamin 

Thank you for reporting.

I confirmed this is a problem of `micromark-extension-definition-list`.
It seems to fail to handle events generated by `micromark-extension-gfm-table`.

I'll see what I can or should do to fix this.

**Comment by wataru-chocola** [comment]
@binyamin 

I've released v1.3.0. Could you try it to see if working as expected?

https://github.com/wataru-chocola/micromark-extension-definition-list/releases/tag/v1.3.0

**Comment by binyamin** [comment]
@wataru-chocola Works for me!
